# Site settings
title: _killpanda
email: angus@killpanda.de
description: > # this means to ignore newlines until "baseurl:"
    I'm you before you shrivelled and died and I don't wanna go where you've been.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://killpanda.github.io" # the base hostname & protocol for your site
twitter_username: _killpanda
github_username:  killpanda

# Build settings
markdown: kramdown
permalink: /:year/:month/:title.html
